var colors = ['red', 'white', 'blue'];
console.log('value of colors[0]:', colors[0]);
console.log('value of colors[1]:', colors[1]);
console.log('value of colors[2]:', colors[2]);
var myString = 'America is ' + colors[0] + ', ' + colors[1] + ', and ' + colors[2] + '.';
console.log(myString);
colors[2] = 'green';
var myNewString = 'Mexico is ' + colors[0] + ', ' + colors[1] + ', and ' + colors[2] + '.';
console.log(myNewString);
console.log('value of colors:', colors);

var students = ['Bishan', 'Brenda', 'Colin', 'Cynthia'];
var numberOfStudents = students.length;
var myNewerString = 'There are ' + numberOfStudents + ' students in the class.';
console.log(myNewerString);
var lastIndex = numberOfStudents - 1;
var lastStudent = students[lastIndex];
var myNewestString = 'The last student in the array is ' + lastStudent + '.';
console.log(myNewestString);
console.log('value of students:', students);
